version: "1"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_USER: bookdb
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookstoredb
    ports:
      - "${MYSQL_EXT_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  bookstore:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bookstore:latest
    ports:
      - "${APP_EXT_PORT}:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/bookstoredb
      - SPRING_DATASOURCE_USERNAME=bookdb
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure
    volumes:
      - c:/users/oknai/.m2/repository:/root/.m2/repository




